### ISSUE TITLE
Fails to install via NPM

### ISSUE THREAD

**Issue by davidjbradshaw** [stoeffel/redux-saga-test#9]
When I install this, I'm missing the `index.js` file

```
dave$ npm install --save-dev redux-saga-test
dave$ ls -l node_modules/redux-saga-test/
total 24
-rw-r--r--  1 dave  staff  1114 25 Nov 09:00 license
-rw-r--r--  1 dave  staff  3069 16 Jan 11:37 package.json
-rw-r--r--  1 dave  staff  1317 25 Nov 09:00 readme.md
dave$ 
```

I'm guessing this is because `package.json` is missing `"main": "index.js",`.

**Comment by aaronjensen** [comment]
Hi @davidjbradshaw, thanks for reporting. It definitely seems like something went wrong when that version was published. I published 1.0.1, which seems to have an index.js. The main field defaults to index.js, so #10 is unnecessary afaict.
